# streamlit settings
mapbox_token = 'pk.eyJ1IjoiaG9iYmVzaWFuIiwiYSI6ImNsZ2dzOTZlZDBlazgzc282YWd3NmIybGQifQ.SQlNC5SSX459RDQ1vyK-qA'

# instrument configurations:
gateways = {asset1="sim_crane1", asset2="sim_crane2", asset3="sim_forklift1"}
beacon_prename = "DD:beacon"
num_beacons = 1

# Insturment comms:
# BLE freq & power settings
channel = "ch39"
power_dBm = 4
systemLoss = 0.2
Channel37Freq_hz = 2.402e9
Channel39Freq_hz = 2.48e9
freqChannelHz = {ch37=2.402e9, ch39=2.48e9}

# Instrument Mechanical settings
RxHeight = 1 #5 # metres
TxHeight = 1 # metres
Crane_TravelSpeed = 2  # m/s
Crane_HookDropLiftRate = 0.1 # m/s

# data map: keys

# Location Settings
## Loc: KXS4
## Map
ROOT = "/home/kiran/source/Working/logisticsDNA/ldna-simulator/"
OSM_Map = "data/CEMCSite/CEMC_map.osm"
## Corner boundaries
LL_Lat = 51.538496800
LL_Lon = -0.125863600
UR_Lat = 51.538356900
UR_Lon = -0.125731600
YardOrientaion_deg = 90

# Lonlat for sites
[[latlon]]
id = 'CEMC'
lon = -1.169802
lat = 53.3058020
#
[[latlon]]
id='KXS4'
lat = 51.5384268499
lon = -0.1257976
#
[[latlon]]
id='FPMcCann'
lat=53.228990
lon=-2.406265
#
[[latlon]]
id='Tinglev'
lat=54.936315
lon=9.261325
#
[[latlon]]
id='Creagh'
lat=54.758098
lon=-6.502816
#
[[latlon]]
id='Oxford'
lat=51.760147
lon=-1.263830
#
[[latlon]]
id='KS'
lat=54.51425
lon=-1.35553